name: NRI SDK
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  Build-Windows:
    runs-on: windows-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install windows-sdk-10.0 cmake -y

      - name: Install Vulkan
        run: |
           $ver = (Invoke-WebRequest -Uri "https://vulkan.lunarg.com/sdk/latest.json" | ConvertFrom-Json).windows
           echo Vulkan SDK version $ver
           $ProgressPreference = 'SilentlyContinue'
           Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/$ver/windows/VulkanSDK-$ver-Installer.exe" -OutFile VulkanSDK.exe
           echo Downloaded
           .\VulkanSDK.exe --root C:\VulkanSDK --accept-licenses --default-answer --confirm-command install

      - name: Deploy
        run: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/"
          $Env:Path += ";C:/VulkanSDK/Bin"
          .\1-Deploy.bat

      - name: Build
        run: |
          $Env:VULKAN_SDK = "C:/VulkanSDK/"
          $Env:Path += ";C:/VulkanSDK/Bin"
          .\2-Build.bat

      - name: Prepare
        run: |
          &'.\3-Prepare NRI SDK.bat' --shaders

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: NRI SDK
          path: _NRI_SDK

  Build-Ubuntu:
    runs-on: ubuntu-22.04
    steps:
      - name : Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.22.x'

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install Vulkan
        run: |
           sudo apt install -y wget
           wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
           sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-jammy.list https://packages.lunarg.com/vulkan/lunarg-vulkan-jammy.list
           sudo apt update
           sudo apt install -y vulkan-sdk libwayland-dev

      - name: Deploy
        run: |
          mkdir "build"
          cd "build"
          cmake -G Ninja ..
          cd ..

      - name: Build
        run: |
          cd "build"
          cmake --build .
          cd ..
